/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    services: Service;
    packages: Package;
    projects: Project;
    leads: Lead;
    signups: Signup;
    'vendor-applications': VendorApplication;
    'phone-verifications': PhoneVerification;
    'vendor-uploads': VendorUpload;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    signups: SignupsSelect<false> | SignupsSelect<true>;
    'vendor-applications': VendorApplicationsSelect<false> | VendorApplicationsSelect<true>;
    'phone-verifications': PhoneVerificationsSelect<false> | PhoneVerificationsSelect<true>;
    'vendor-uploads': VendorUploadsSelect<false> | VendorUploadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload gallery and site images here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Shown to screen readers and if the image fails to load.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Categories used to organise the gallery and packages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL identifier. Leave blank to auto-generate from the title.
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Optional cover image for this event type.
   */
  image?: (number | null) | Media;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL identifier. Leave blank to auto-generate from the title.
   */
  slug?: string | null;
  /**
   * One short line shown on cards.
   */
  summary?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Highlight on the home page.
   */
  featured?: boolean | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  title: string;
  /**
   * URL identifier. Leave blank to auto-generate from the title.
   */
  slug?: string | null;
  /**
   * Short one-liner.
   */
  tagline?: string | null;
  image?: (number | null) | Media;
  /**
   * Which event types this package suits.
   */
  idealFor?: (number | Category)[] | null;
  includedServices?: (number | Service)[] | null;
  /**
   * Bullet points shown on the package card.
   */
  highlights?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "Starting from ₹75,000" or "Custom quote". Optional.
   */
  priceNote?: string | null;
  /**
   * Highlight on the home page.
   */
  featured?: boolean | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Your past events. Clients decide based on these photos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL identifier. Leave blank to auto-generate from the title.
   */
  slug?: string | null;
  /**
   * Event type — used for gallery filtering.
   */
  category: number | Category;
  /**
   * Main image shown in the gallery grid.
   */
  coverImage: number | Media;
  /**
   * All photos for this event (shown in the lightbox).
   */
  photos?: (number | Media)[] | null;
  description?: string | null;
  branch?: ('guduvancheri' | 'thiruverkadu') | null;
  location?: string | null;
  date?: string | null;
  /**
   * Show on the home page.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Enquiries submitted through the website. Call these back.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  eventType?: ('wedding' | 'birthday' | 'corporate' | 'housewarming' | 'sports' | 'other') | null;
  eventDate?: string | null;
  branch?: ('guduvancheri' | 'thiruverkadu' | 'any') | null;
  message?: string | null;
  status?: ('new' | 'contacted' | 'quoted' | 'booked' | 'closed') | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who signed up for the ₹100-off offer. Honour the discount when quoting.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signups".
 */
export interface Signup {
  id: number;
  name: string;
  phone: string;
  birthday: string;
  planningEvent: 'yes' | 'no';
  eventType?: ('wedding' | 'birthday' | 'corporate' | 'housewarming' | 'sports' | 'other') | null;
  eventDate?: string | null;
  guestCount?: number | null;
  message?: string | null;
  status?: ('new' | 'contacted' | 'redeemed' | 'closed') | null;
  offer?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vendors who want to work with Zenfest Events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-applications".
 */
export interface VendorApplication {
  id: number;
  name: string;
  businessName?: string | null;
  vendorType: 'photography' | 'cake' | 'decoration' | 'catering' | 'dj' | 'other';
  /**
   * What the vendor offers, when they chose "Other".
   */
  otherService?: string | null;
  photography?: {
    coverage?: ('single' | 'all') | null;
    specialty?: ('traditional-photo' | 'traditional-video' | 'candid-photo' | 'candid-video' | 'drone') | null;
    rates?:
      | {
          service: 'traditional-photo' | 'traditional-video' | 'candid-photo' | 'candid-video' | 'drone';
          /**
           * 1 session ≈ 5 hours.
           */
          sessionPrice?: number | null;
          camera?: string | null;
          id?: string | null;
        }[]
      | null;
    editing?: ('album-traditional' | 'album-candid' | 'video-traditional' | 'video-candid')[] | null;
  };
  cake?: {
    flavours?:
      | {
          flavour: string;
          ratePerKg?: number | null;
          id?: string | null;
        }[]
      | null;
    menu?: (number | null) | VendorUpload;
    egglessCharge?: number | null;
    egglessUnit?: ('per-kg' | 'flat' | 'nil' | 'none') | null;
    wheatCharge?: number | null;
    wheatUnit?: ('per-kg' | 'flat' | 'nil' | 'none') | null;
    tier2kgCharge?: number | null;
    tier3kgCharge?: number | null;
    tierUnit?: ('flat' | 'per-kg' | 'none') | null;
    customCharge?: number | null;
    customUnit?: ('per-cake' | 'per-kg' | 'none') | null;
    minOrder?: ('half-kg' | '1kg') | null;
    leadNormalDays?: number | null;
    leadCustomDays?: number | null;
    fssaiNumber?: string | null;
    fssaiCertificate?: (number | null) | VendorUpload;
    deliveryRadiusKm?: number | null;
    deliveryRates?: string | null;
    venueServing?: ('yes' | 'no') | null;
  };
  phone: string;
  phoneVerified?: boolean | null;
  phoneVerification?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  email?: string | null;
  city?: string | null;
  /**
   * Link to work samples / Instagram / website.
   */
  portfolioUrl?: string | null;
  message?: string | null;
  status?: ('new' | 'reviewing' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * FSSAI certificates and menu cards sent with vendor applications.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-uploads".
 */
export interface VendorUpload {
  id: number;
  kind: 'fssai' | 'menu' | 'other';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * WhatsApp phone checks from the website forms. Created automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phone-verifications".
 */
export interface PhoneVerification {
  id: number;
  phone: string;
  code: string;
  token: string;
  status: 'pending' | 'verified' | 'used';
  purpose?: string | null;
  expiresAt: string;
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'signups';
        value: number | Signup;
      } | null)
    | ({
        relationTo: 'vendor-applications';
        value: number | VendorApplication;
      } | null)
    | ({
        relationTo: 'phone-verifications';
        value: number | PhoneVerification;
      } | null)
    | ({
        relationTo: 'vendor-uploads';
        value: number | VendorUpload;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  image?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tagline?: T;
  image?: T;
  idealFor?: T;
  includedServices?: T;
  highlights?:
    | T
    | {
        item?: T;
        id?: T;
      };
  priceNote?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  coverImage?: T;
  photos?: T;
  description?: T;
  branch?: T;
  location?: T;
  date?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  eventType?: T;
  eventDate?: T;
  branch?: T;
  message?: T;
  status?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signups_select".
 */
export interface SignupsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  birthday?: T;
  planningEvent?: T;
  eventType?: T;
  eventDate?: T;
  guestCount?: T;
  message?: T;
  status?: T;
  offer?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-applications_select".
 */
export interface VendorApplicationsSelect<T extends boolean = true> {
  name?: T;
  businessName?: T;
  vendorType?: T;
  otherService?: T;
  photography?:
    | T
    | {
        coverage?: T;
        specialty?: T;
        rates?:
          | T
          | {
              service?: T;
              sessionPrice?: T;
              camera?: T;
              id?: T;
            };
        editing?: T;
      };
  cake?:
    | T
    | {
        flavours?:
          | T
          | {
              flavour?: T;
              ratePerKg?: T;
              id?: T;
            };
        menu?: T;
        egglessCharge?: T;
        egglessUnit?: T;
        wheatCharge?: T;
        wheatUnit?: T;
        tier2kgCharge?: T;
        tier3kgCharge?: T;
        tierUnit?: T;
        customCharge?: T;
        customUnit?: T;
        minOrder?: T;
        leadNormalDays?: T;
        leadCustomDays?: T;
        fssaiNumber?: T;
        fssaiCertificate?: T;
        deliveryRadiusKm?: T;
        deliveryRates?: T;
        venueServing?: T;
      };
  phone?: T;
  phoneVerified?: T;
  phoneVerification?: T;
  email?: T;
  city?: T;
  portfolioUrl?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phone-verifications_select".
 */
export interface PhoneVerificationsSelect<T extends boolean = true> {
  phone?: T;
  code?: T;
  token?: T;
  status?: T;
  purpose?: T;
  expiresAt?: T;
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-uploads_select".
 */
export interface VendorUploadsSelect<T extends boolean = true> {
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details, branches and homepage text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  hero?: {
    headline?: string | null;
    subheadline?: string | null;
  };
  contact?: {
    phonePrimary?: string | null;
    phoneSecondary?: string | null;
    /**
     * Full international format, digits only, e.g. 919876543210.
     */
    whatsapp?: string | null;
    email?: string | null;
    hours?: string | null;
  };
  /**
   * Your office locations.
   */
  branches?:
    | {
        name: string;
        addressLine?: string | null;
        phone?: string | null;
        mapUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    youtube?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
      };
  contact?:
    | T
    | {
        phonePrimary?: T;
        phoneSecondary?: T;
        whatsapp?: T;
        email?: T;
        hours?: T;
      };
  branches?:
    | T
    | {
        name?: T;
        addressLine?: T;
        phone?: T;
        mapUrl?: T;
        id?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}