/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    services: Service;
    packages: Package;
    projects: Project;
    leads: Lead;
    signups: Signup;
    'vendor-applications': VendorApplication;
    'phone-verifications': PhoneVerification;
    'vendor-uploads': VendorUpload;
    'host-applications': HostApplication;
    'registry-events': RegistryEvent;
    'registry-items': RegistryItem;
    'registry-claims': RegistryClaim;
    'registry-clicks': RegistryClick;
    'registry-guests': RegistryGuest;
    'registry-leads': RegistryLead;
    polls: Poll;
    'poll-votes': PollVote;
    'poll-voters': PollVoter;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    signups: SignupsSelect<false> | SignupsSelect<true>;
    'vendor-applications': VendorApplicationsSelect<false> | VendorApplicationsSelect<true>;
    'phone-verifications': PhoneVerificationsSelect<false> | PhoneVerificationsSelect<true>;
    'vendor-uploads': VendorUploadsSelect<false> | VendorUploadsSelect<true>;
    'host-applications': HostApplicationsSelect<false> | HostApplicationsSelect<true>;
    'registry-events': RegistryEventsSelect<false> | RegistryEventsSelect<true>;
    'registry-items': RegistryItemsSelect<false> | RegistryItemsSelect<true>;
    'registry-claims': RegistryClaimsSelect<false> | RegistryClaimsSelect<true>;
    'registry-clicks': RegistryClicksSelect<false> | RegistryClicksSelect<true>;
    'registry-guests': RegistryGuestsSelect<false> | RegistryGuestsSelect<true>;
    'registry-leads': RegistryLeadsSelect<false> | RegistryLeadsSelect<true>;
    polls: PollsSelect<false> | PollsSelect<true>;
    'poll-votes': PollVotesSelect<false> | PollVotesSelect<true>;
    'poll-voters': PollVotersSelect<false> | PollVotersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload gallery and site images here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Shown to screen readers and if the image fails to load.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Categories used to organise the gallery and packages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL identifier. Leave blank to auto-generate from the title.
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Optional cover image for this event type.
   */
  image?: (number | null) | Media;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL identifier. Leave blank to auto-generate from the title.
   */
  slug?: string | null;
  /**
   * One short line shown on cards.
   */
  summary?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Highlight on the home page.
   */
  featured?: boolean | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  title: string;
  /**
   * URL identifier. Leave blank to auto-generate from the title.
   */
  slug?: string | null;
  /**
   * Short one-liner.
   */
  tagline?: string | null;
  image?: (number | null) | Media;
  /**
   * Which event types this package suits.
   */
  idealFor?: (number | Category)[] | null;
  includedServices?: (number | Service)[] | null;
  /**
   * Bullet points shown on the package card.
   */
  highlights?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "Starting from ₹75,000" or "Custom quote". Optional.
   */
  priceNote?: string | null;
  /**
   * Highlight on the home page.
   */
  featured?: boolean | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Your past events. Clients decide based on these photos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL identifier. Leave blank to auto-generate from the title.
   */
  slug?: string | null;
  /**
   * Event type — used for gallery filtering.
   */
  category: number | Category;
  /**
   * Main image shown in the gallery grid.
   */
  coverImage: number | Media;
  /**
   * All photos for this event (shown in the lightbox).
   */
  photos?: (number | Media)[] | null;
  description?: string | null;
  branch?: ('guduvancheri' | 'thiruverkadu') | null;
  location?: string | null;
  date?: string | null;
  /**
   * Show on the home page.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Enquiries submitted through the website. Call these back.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  eventType?: ('wedding' | 'birthday' | 'corporate' | 'housewarming' | 'sports' | 'other') | null;
  eventDate?: string | null;
  branch?: ('guduvancheri' | 'thiruverkadu' | 'any') | null;
  message?: string | null;
  status?: ('new' | 'contacted' | 'quoted' | 'booked' | 'closed') | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who signed up for the ₹100-off offer. Honour the discount when quoting.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signups".
 */
export interface Signup {
  id: number;
  name: string;
  phone: string;
  birthday: string;
  planningEvent: 'yes' | 'no';
  eventType?: ('wedding' | 'birthday' | 'corporate' | 'housewarming' | 'sports' | 'other') | null;
  eventDate?: string | null;
  guestCount?: number | null;
  message?: string | null;
  status?: ('new' | 'contacted' | 'redeemed' | 'closed') | null;
  offer?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vendors who want to work with Zenfest Events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-applications".
 */
export interface VendorApplication {
  id: number;
  name: string;
  businessName?: string | null;
  vendorType: 'photography' | 'cake' | 'decoration' | 'catering' | 'dj' | 'other';
  /**
   * What the vendor offers, when they chose "Other".
   */
  otherService?: string | null;
  photography?: {
    coverage?: ('single' | 'all') | null;
    specialty?: ('traditional-photo' | 'traditional-video' | 'candid-photo' | 'candid-video' | 'drone') | null;
    rates?:
      | {
          service: 'traditional-photo' | 'traditional-video' | 'candid-photo' | 'candid-video' | 'drone';
          /**
           * 1 session ≈ 5 hours.
           */
          sessionPrice?: number | null;
          camera?: string | null;
          id?: string | null;
        }[]
      | null;
    editing?: ('album-traditional' | 'album-candid' | 'video-traditional' | 'video-candid')[] | null;
  };
  cake?: {
    flavours?:
      | {
          flavour: string;
          ratePerKg?: number | null;
          id?: string | null;
        }[]
      | null;
    menu?: (number | null) | VendorUpload;
    egglessCharge?: number | null;
    egglessUnit?: ('per-kg' | 'flat' | 'nil' | 'none') | null;
    wheatCharge?: number | null;
    wheatUnit?: ('per-kg' | 'flat' | 'nil' | 'none') | null;
    tier2kgCharge?: number | null;
    tier3kgCharge?: number | null;
    tierUnit?: ('flat' | 'per-kg' | 'none') | null;
    customCharge?: number | null;
    customUnit?: ('per-cake' | 'per-kg' | 'none') | null;
    minOrder?: ('half-kg' | '1kg') | null;
    leadNormalDays?: number | null;
    leadCustomDays?: number | null;
    fssaiNumber?: string | null;
    fssaiCertificate?: (number | null) | VendorUpload;
    deliveryRadiusKm?: number | null;
    deliveryRates?: string | null;
    venueServing?: ('yes' | 'no') | null;
  };
  phone: string;
  phoneVerified?: boolean | null;
  phoneVerification?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  email?: string | null;
  city?: string | null;
  /**
   * Link to work samples / Instagram / website.
   */
  portfolioUrl?: string | null;
  message?: string | null;
  status?: ('new' | 'reviewing' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * FSSAI certificates and menu cards sent with vendor applications.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-uploads".
 */
export interface VendorUpload {
  id: number;
  kind: 'fssai' | 'menu' | 'other';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * WhatsApp phone checks from the website forms. Created automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phone-verifications".
 */
export interface PhoneVerification {
  id: number;
  phone: string;
  code: string;
  token: string;
  status: 'pending' | 'verified' | 'used';
  purpose?: string | null;
  expiresAt: string;
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Families who want to host foreign guests at their event (/earn). Verify the family before listing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "host-applications".
 */
export interface HostApplication {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  relation?: ('couple' | 'parent' | 'sibling' | 'relative' | 'other') | null;
  eventType:
    | 'wedding'
    | 'engagement'
    | 'reception'
    | 'valaikappu'
    | 'puberty'
    | 'naming'
    | 'ear-piercing'
    | 'housewarming'
    | 'festival'
    | 'other';
  eventDate: string;
  days: '1' | '2' | '3+';
  city:
    | 'chennai'
    | 'coimbatore'
    | 'madurai'
    | 'tiruchirappalli'
    | 'salem'
    | 'tirunelveli'
    | 'vellore'
    | 'thanjavur'
    | 'erode'
    | 'tiruppur'
    | 'kanchipuram'
    | 'other-tn';
  venueArea?: string | null;
  language?: ('tamil' | 'telugu' | 'malayalam' | 'kannada' | 'hindi' | 'other') | null;
  guestCount?: number | null;
  touristSeats: '1-2' | '3-5' | '6+';
  experiences?: ('meals' | 'dress-up' | 'mehendi' | 'buddy' | 'photos' | 'stay')[] | null;
  englishSpeaker?: ('yes' | 'no') | null;
  rituals?: string | null;
  message?: string | null;
  consent: boolean;
  status?: ('new' | 'contacted' | 'verified' | 'listed' | 'declined' | 'closed') | null;
  /**
   * Internal — guests matched, amounts, paid date.
   */
  payoutNotes?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gift registries made by families at /registry. Every new one is also a warm lead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registry-events".
 */
export interface RegistryEvent {
  id: number;
  slug: string;
  title: string;
  eventType:
    | 'wedding'
    | 'engagement'
    | 'reception'
    | 'housewarming'
    | 'birthday'
    | 'baby-shower'
    | 'naming'
    | 'pooja'
    | 'anniversary'
    | 'other';
  hostNames?: string | null;
  eventDate: string;
  venueName?: string | null;
  venueCity?: string | null;
  venueMapUrl?: string | null;
  welcomeNote?: string | null;
  /**
   * Guests pay the family directly — no money passes through Zenfest.
   */
  upiId?: string | null;
  upiName?: string | null;
  /**
   * Off = surprise mode: the host sees counts only.
   */
  revealClaims?: boolean | null;
  hostName: string;
  hostPhone: string;
  hostEmail?: string | null;
  manageKeyHash: string;
  /**
   * Hidden registries show “not found” to guests.
   */
  status?: ('active' | 'hidden') | null;
  leadStatus?: ('new' | 'contacted' | 'booked' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registry-items".
 */
export interface RegistryItem {
  id: number;
  event: number | RegistryEvent;
  itemType: 'affiliate_link' | 'custom_offline' | 'cash_fund';
  title: string;
  price?: number | null;
  imageUrl?: string | null;
  originalUrl?: string | null;
  merchant?: string | null;
  note?: string | null;
  targetAmount?: number | null;
  /**
   * Updated by the host as shagun arrives (guests pay the family directly).
   */
  raisedAmount?: number | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Delete a claim to make the gift available again.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registry-claims".
 */
export interface RegistryClaim {
  id: number;
  item: number | RegistryItem;
  event: number | RegistryEvent;
  guestName: string;
  message?: string | null;
  mode?: ('online' | 'offline') | null;
  undoTokenHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registry-clicks".
 */
export interface RegistryClick {
  id: number;
  item?: (number | null) | RegistryItem;
  event?: (number | null) | RegistryEvent;
  merchant?: string | null;
  affiliated?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registry-guests".
 */
export interface RegistryGuest {
  id: number;
  event: number | RegistryEvent;
  name: string;
  phone?: string | null;
  side?: ('family' | 'friends' | 'work' | 'other') | null;
  count?: number | null;
  rsvp?: ('pending' | 'yes' | 'maybe' | 'no') | null;
  invitedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Guests who tapped “Plan with Zenfest” on someone’s registry. Call or WhatsApp them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registry-leads".
 */
export interface RegistryLead {
  id: number;
  name: string;
  phone: string;
  eventType?: ('wedding' | 'birthday' | 'corporate' | 'housewarming' | 'other') | null;
  tentativeDate?: string | null;
  city?: string | null;
  /**
   * Slug of the registry the guest was viewing.
   */
  referringEvent?: string | null;
  status?: ('new' | 'contacted' | 'quoted' | 'booked' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Open a poll by setting Status to Open. It closes by itself at “Closes at”. Event polls (with a registry) are managed by the family.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "polls".
 */
export interface Poll {
  id: number;
  question: string;
  /**
   * Filled in automatically from the question if left blank.
   */
  slug?: string | null;
  category: 'sports' | 'entertainment' | 'food' | 'lifestyle' | 'politics' | 'civic' | 'event';
  description?: string | null;
  image?: (number | null) | Media;
  options: {
    label: string;
    id?: string | null;
  }[];
  status: 'draft' | 'open' | 'closed';
  /**
   * Leave blank to keep it open until you close it.
   */
  closesAt?: string | null;
  /**
   * Shown at the top of /polls and on the homepage.
   */
  featured?: boolean | null;
  resultsVisibility?: ('after-vote' | 'always' | 'after-close') | null;
  /**
   * Only applies once phone verification is live. Event polls never ask.
   */
  requireVerified?: boolean | null;
  /**
   * Hides results while open and shows an “opinion poll, not a prediction” note. Close it during the Election Commission’s silence period.
   */
  electionSensitive?: boolean | null;
  registryEvent?: (number | null) | RegistryEvent;
  sponsor?: {
    name?: string | null;
    logo?: (number | null) | Media;
    url?: string | null;
  };
  /**
   * Shown after voting. Blank = the default for the category.
   */
  cta?: {
    text?: string | null;
    label?: string | null;
    href?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poll-votes".
 */
export interface PollVote {
  id: number;
  poll: number | Poll;
  optionId: string;
  voterKey: string;
  voter?: (number | null) | PollVoter;
  verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Only contact people with “Agreed to updates” ticked.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poll-voters".
 */
export interface PollVoter {
  id: number;
  phone: string;
  phoneVerified?: boolean | null;
  marketingConsent?: boolean | null;
  consentAt?: string | null;
  votes?: number | null;
  lastVotedAt?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'signups';
        value: number | Signup;
      } | null)
    | ({
        relationTo: 'vendor-applications';
        value: number | VendorApplication;
      } | null)
    | ({
        relationTo: 'phone-verifications';
        value: number | PhoneVerification;
      } | null)
    | ({
        relationTo: 'vendor-uploads';
        value: number | VendorUpload;
      } | null)
    | ({
        relationTo: 'host-applications';
        value: number | HostApplication;
      } | null)
    | ({
        relationTo: 'registry-events';
        value: number | RegistryEvent;
      } | null)
    | ({
        relationTo: 'registry-items';
        value: number | RegistryItem;
      } | null)
    | ({
        relationTo: 'registry-claims';
        value: number | RegistryClaim;
      } | null)
    | ({
        relationTo: 'registry-clicks';
        value: number | RegistryClick;
      } | null)
    | ({
        relationTo: 'registry-guests';
        value: number | RegistryGuest;
      } | null)
    | ({
        relationTo: 'registry-leads';
        value: number | RegistryLead;
      } | null)
    | ({
        relationTo: 'polls';
        value: number | Poll;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  image?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tagline?: T;
  image?: T;
  idealFor?: T;
  includedServices?: T;
  highlights?:
    | T
    | {
        item?: T;
        id?: T;
      };
  priceNote?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  coverImage?: T;
  photos?: T;
  description?: T;
  branch?: T;
  location?: T;
  date?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  eventType?: T;
  eventDate?: T;
  branch?: T;
  message?: T;
  status?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signups_select".
 */
export interface SignupsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  birthday?: T;
  planningEvent?: T;
  eventType?: T;
  eventDate?: T;
  guestCount?: T;
  message?: T;
  status?: T;
  offer?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-applications_select".
 */
export interface VendorApplicationsSelect<T extends boolean = true> {
  name?: T;
  businessName?: T;
  vendorType?: T;
  otherService?: T;
  photography?:
    | T
    | {
        coverage?: T;
        specialty?: T;
        rates?:
          | T
          | {
              service?: T;
              sessionPrice?: T;
              camera?: T;
              id?: T;
            };
        editing?: T;
      };
  cake?:
    | T
    | {
        flavours?:
          | T
          | {
              flavour?: T;
              ratePerKg?: T;
              id?: T;
            };
        menu?: T;
        egglessCharge?: T;
        egglessUnit?: T;
        wheatCharge?: T;
        wheatUnit?: T;
        tier2kgCharge?: T;
        tier3kgCharge?: T;
        tierUnit?: T;
        customCharge?: T;
        customUnit?: T;
        minOrder?: T;
        leadNormalDays?: T;
        leadCustomDays?: T;
        fssaiNumber?: T;
        fssaiCertificate?: T;
        deliveryRadiusKm?: T;
        deliveryRates?: T;
        venueServing?: T;
      };
  phone?: T;
  phoneVerified?: T;
  phoneVerification?: T;
  email?: T;
  city?: T;
  portfolioUrl?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phone-verifications_select".
 */
export interface PhoneVerificationsSelect<T extends boolean = true> {
  phone?: T;
  code?: T;
  token?: T;
  status?: T;
  purpose?: T;
  expiresAt?: T;
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-uploads_select".
 */
export interface VendorUploadsSelect<T extends boolean = true> {
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "host-applications_select".
 */
export interface HostApplicationsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  relation?: T;
  eventType?: T;
  eventDate?: T;
  days?: T;
  city?: T;
  venueArea?: T;
  language?: T;
  guestCount?: T;
  touristSeats?: T;
  experiences?: T;
  englishSpeaker?: T;
  rituals?: T;
  message?: T;
  consent?: T;
  status?: T;
  payoutNotes?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registry-events_select".
 */
export interface RegistryEventsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  eventType?: T;
  hostNames?: T;
  eventDate?: T;
  venueName?: T;
  venueCity?: T;
  venueMapUrl?: T;
  welcomeNote?: T;
  upiId?: T;
  upiName?: T;
  revealClaims?: T;
  hostName?: T;
  hostPhone?: T;
  hostEmail?: T;
  manageKeyHash?: T;
  status?: T;
  leadStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registry-items_select".
 */
export interface RegistryItemsSelect<T extends boolean = true> {
  event?: T;
  itemType?: T;
  title?: T;
  price?: T;
  imageUrl?: T;
  originalUrl?: T;
  merchant?: T;
  note?: T;
  targetAmount?: T;
  raisedAmount?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registry-claims_select".
 */
export interface RegistryClaimsSelect<T extends boolean = true> {
  item?: T;
  event?: T;
  guestName?: T;
  message?: T;
  mode?: T;
  undoTokenHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registry-clicks_select".
 */
export interface RegistryClicksSelect<T extends boolean = true> {
  item?: T;
  event?: T;
  merchant?: T;
  affiliated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registry-guests_select".
 */
export interface RegistryGuestsSelect<T extends boolean = true> {
  event?: T;
  name?: T;
  phone?: T;
  side?: T;
  count?: T;
  rsvp?: T;
  invitedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registry-leads_select".
 */
export interface RegistryLeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  eventType?: T;
  tentativeDate?: T;
  city?: T;
  referringEvent?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "polls_select".
 */
export interface PollsSelect<T extends boolean = true> {
  question?: T;
  slug?: T;
  category?: T;
  description?: T;
  image?: T;
  options?:
    | T
    | {
        label?: T;
        id?: T;
      };
  status?: T;
  closesAt?: T;
  featured?: T;
  resultsVisibility?: T;
  requireVerified?: T;
  electionSensitive?: T;
  registryEvent?: T;
  sponsor?:
    | T
    | {
        name?: T;
        logo?: T;
        url?: T;
      };
  cta?:
    | T
    | {
        text?: T;
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poll-votes_select".
 */
export interface PollVotesSelect<T extends boolean = true> {
  poll?: T;
  optionId?: T;
  voterKey?: T;
  voter?: T;
  verified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poll-voters_select".
 */
export interface PollVotersSelect<T extends boolean = true> {
  phone?: T;
  phoneVerified?: T;
  marketingConsent?: T;
  consentAt?: T;
  votes?: T;
  lastVotedAt?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details, branches and homepage text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  hero?: {
    headline?: string | null;
    subheadline?: string | null;
  };
  contact?: {
    phonePrimary?: string | null;
    phoneSecondary?: string | null;
    /**
     * Full international format, digits only, e.g. 919876543210.
     */
    whatsapp?: string | null;
    email?: string | null;
    hours?: string | null;
  };
  /**
   * Your office locations.
   */
  branches?:
    | {
        name: string;
        addressLine?: string | null;
        phone?: string | null;
        mapUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    youtube?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
      };
  contact?:
    | T
    | {
        phonePrimary?: T;
        phoneSecondary?: T;
        whatsapp?: T;
        email?: T;
        hours?: T;
      };
  branches?:
    | T
    | {
        name?: T;
        addressLine?: T;
        phone?: T;
        mapUrl?: T;
        id?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}